version: "3.1"

services:
  database:
    build: 
       context: ./database
    image: api_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: api_db
    ports:
      - "5432:5432" 
    networks:
      - back-network
    secrets:
      - postgres_password

  api:
    build:
       context: .
       dockerfile: Dockerfile
    image: api_app
    ports:
      - "8080:8080"
    networks:
      - back-network
    secrets:
      - postgres_password

secrets:
  postgres_password:
    file: ./devsecrets/postgres_password
    
networks:
  back-network:
    driver: bridge
